### ISSUE TITLE
关于Fusformer的训练测试

### ISSUE THREAD

**Issue by tarxs** [Caoxuheng/HIFtool#3]
作者你好：
使用chikusei训练Fusformer
在训练时，CUDA out of memory，我将batch size从2改成1，可以进行训练。但是测试的时候out of memory。我想使用
```
output_HRHSI = torch.empty_like(GT)
            t = 4
            sf = 4
            n_ = GT.shape[2]
            for i in range(t):
               for j in range(t):
                   n = n_//t
                   output_HRHSI[:,:,i*n:(i+1)*n,j*n:(j+1)*n] = model(LRHSI[:,:,i*n//sf:(i+1)*n//sf,j*n//sf:(j+1)*n//sf],
                                                                     HRMSI[:,:,i*n:(i+1)*n,j*n:(j+1)*n])
```
是否是在训练的时候使用的是512x512的图片，所以网络是512的；而测试的时候拆分后图片是128x128，二者不对应。是否应该在训练的时候同样拆分图片，还是改什么超参数就行？

**Comment by Caoxuheng** [comment]
是的，训练时是512的，因此测试必须是512。如果使用分块，训练的时候就应该分t^2块。  
如果你想继续使用这个权重，可以尝试在cpu跑一下。不过我记得FusFormer对内存的要求非常苛刻，可能一般工作站的内存也很难跑下来一张图像。

**Comment by tarxs** [comment]
能否告知一下你们是如何处理的？如果在训练时把网络分成若干块，我很担心分块的地方会出现没有对齐的现象

**Comment by Caoxuheng** [comment]
在我训练时，分块训练产生的块效应在波段图上是人眼看不到的，热力图能看到。 该算法的作者针对显存的问题给出过解释，如果显存不够，就需要分块训练。 更多细节也可以询问fusformer 的作者们。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月16日 00:28 |
| 收件人 | Caoxuheng/HIFtool ***@***.***> |
| 抄送人 | Xuheng ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Caoxuheng/HIFtool] 关于Fusformer的训练测试 (Issue #3) |

能否告知一下你们是如何处理的？如果在训练时把网络分成若干块，我很担心分块的地方会出现没有对齐的现象

**Comment by tarxs** [comment]
非常抱歉询问了和你们代码不相关的问题，同时感谢你的回复
