### ISSUE TITLE
spectral response

### ISSUE THREAD

**Issue by LRuiRui517** [Caoxuheng/HIFtool#5]
Hello, do you have the spectral response data file corresponding to the Xiongan dataset?

**Comment by Caoxuheng** [comment]
伊科诺斯的波数范围包含雄安的波数范围，可以直接使用Chikuseisrf.mat作为光谱响应。

**Comment by LRuiRui517** [comment]
您好，这个Chikuseisrf.mat文件在哪里下载，我没有找到。

**Comment by Caoxuheng** [comment]
[点击](https://github.com/Caoxuheng/HIFtool/blob/main/Dataloader_tool/srflib/chikuseisrf.mat)下载

**Comment by LRuiRui517** [comment]
好的，非常感谢。还想请问一下，pavia和QB的光谱响应数据可以用哪些数据呢？谢谢~

**Comment by Caoxuheng** [comment]
pavia也是伊科诺斯。QB没有光谱响应，训练权重都是监督训练的权重。在做非盲融合的时候，我是用HySure或者uHNTC解出来的空谱退化。

**Comment by LRuiRui517** [comment]
好的好的 非常感谢！
