### ISSUE TITLE
有关论文排版的一些疑惑

### ISSUE THREAD

**Issue by SilentWu** [Caoxuheng/HIFtool#9]
想请教一个论文排版的问题，就是latex的格式是如何实现论文参考文献反向跳转。如图所示，在你的论文中点击Reference部分的[53]可以跳转到页面9。我在overleaf排版我的论文时，也想实现这种跳转方式。但是在网上搜索了好多答案，都没有成功实现。所以想请教你是怎么做到的
![图片1](https://github.com/user-attachments/assets/11714239-c9b6-4266-a6f3-859a9ada3099)

**Comment by Caoxuheng** [comment]
用Endnote插入文献，在设置里把link打开即可。文章接受后出版商也会进行重拍版

**Comment by SilentWu** [comment]
非常感谢你的回答
